_name_: etth
size:
  - 384
  - 96
  - 48
features: 'M'
target: 'OT'
variant: 0
scale: True
inverse: False
timeenc: 1
eval_stamp: False
eval_mask: False
# freq: 'h' # Shouldn't touch
__l_max: ${eval:${.size.0}+${.size.2}}
